Optimize setup-chains

diff --git a/fixture/chain/setup-chains.sh.in b/fixture/chain/setup-chains.sh.in
--- a/fixture/chain/setup-chains.sh.in
+++ b/fixture/chain/setup-chains.sh.in
@@ -14,15 +14,92 @@ prepare_cosmovisor() {
 	fi
 }
 
+initialize() {
+	local region_index=$1
+	local chain_index=$2
+
+	local admin=$(service_name administrator $region_index $chain_index)
+
+	service_exec $admin "cd && ansible-playbook -i inventory initialize.yml \\
+-e daemon_name=@DAEMON_NAME@ \\
+-e daemon_home=@DAEMON_HOME@ \\
+-e region_index=$region_index \\
+-e chain_index=$chain_index \\
+-e config_timeout_propose=@FIXTURE_CONFIG_TIMEOUT_PROPOSE@ \\
+-e config_timeout_prevote=@FIXTURE_CONFIG_TIMEOUT_PREVOTE@ \\
+-e config_timeout_precommit=@FIXTURE_CONFIG_TIMEOUT_PRECOMMIT@ \\
+-e config_timeout_commit=@FIXTURE_CONFIG_TIMEOUT_COMMIT@ \\
+-e client_keyring_backend=@FIXTURE_CLIENT_KEYRING_BACKEND@"
+}
+
+generate_gentxs() {
+	local region_index=$1
+	local chain_index=$2
+
+	local admin=$(service_name administrator $region_index $chain_index)
+
+	service_exec $admin "cd && ansible-playbook -i inventory genesis.yml \\
+-e phase=generate \\
+-e daemon_name=@DAEMON_NAME@ \\
+-e daemon_home=@DAEMON_HOME@ \\
+-e region_index=$region_index \\
+-e chain_index=$chain_index \\
+-e state_bond_denom=@FIXTURE_STATE_BOND_DENOM@ \\
+-e state_balance=@FIXTURE_STATE_BALANCE@ \\
+-e state_delegation=@FIXTURE_STATE_DELEGATION@"
+	service_fetch $admin /root/artifact/seat/address.txt $_genesis_dir/address-$region_index.txt
+	service_fetch $admin /root/artifact/seat/gentx.json $_genesis_dir/gentx-$region_index.json
+}
+
+distribute_genesis() {
+	local region_index=$1
+	local chain_index=$2
+
+	local admin=$(service_name administrator $region_index $chain_index)
+
+	service_exec $admin "mkdir -p /root/artifact/genesis"
+	service_push $admin $_genesis_dir/genesis.json /root/artifact/genesis/
+	service_exec $admin "cd && ansible-playbook -i inventory genesis.yml \\
+-e phase=distribute \\
+-e daemon_home=@DAEMON_HOME@"
+}
+
+gather_configs() {
+	local region_index=$1
+	local chain_index=$2
+
+	local admin=$(service_name administrator $region_index $chain_index)
+
+	service_exec $admin "cd && ansible-playbook -i inventory config.yml \\
+-e phase=gather"
+	mkdir $_dynamic_dir/$region_index
+	service_fetch $admin /root/artifact/seed/public-ip.txt $_dynamic_dir/$region_index/
+	service_fetch $admin /root/artifact/seed/node-id.txt $_dynamic_dir/$region_index/
+}
+
+apply_configs() {
+	local region_index=$1
+	local chain_index=$2
+
+	local admin=$(service_name administrator $region_index $chain_index)
+
+	service_exec $admin "mkdir -p /root/artifact/seeds"
+	service_push $admin $_dynamic_dir/. /root/artifact/seeds/
+	service_exec $admin "cd && ansible-playbook -i inventory config.yml \\
+-e phase=apply \\
+-e daemon_home=@DAEMON_HOME@ \\
+-e region_index=$region_index"
+}
+
 assert_variables NUM_CHAINS \
 				 NUM_REGIONS \
 				 NUM_SENTRIES
 
 prepare_cosmovisor
 
-# prepare binaries on admin
 for _ci in $(seq 0 $(expr $NUM_CHAINS - 1))
 do
+	# prepare binaries on admin
 	for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
 	do
 		_admin=$(service_name administrator $_ri $_ci)
@@ -33,11 +110,7 @@ do
 		# service_push $_admin @DAEMON_BINARY_DIR@/$_version/bundle.tar.gz ~/daemon/$_version/
 		service_push $_admin @DAEMON_BINARY_DIR@/$_version/bundle.tar.gz "/root/"
 	done
-done
 
-# generate genesis
-for _ci in $(seq 0 $(expr $NUM_CHAINS - 1))
-do
 	_genesis_dir=genesis/$_ci
 	rm -rf $_genesis_dir
 	mkdir -p $_genesis_dir
@@ -47,41 +120,24 @@ do
 	mkdir -p $_dynamic_dir
 
 	# initialize
+	_pending_pids=
 	for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
 	do
-		_admin=$(service_name administrator $_ri $_ci)
-
-		service_exec $_admin "cd && ansible-playbook -i inventory initialize.yml \\
--e daemon_name=@DAEMON_NAME@ \\
--e daemon_home=@DAEMON_HOME@ \\
--e region_index=$_ri \\
--e chain_index=$_ci \\
--e config_timeout_propose=@FIXTURE_CONFIG_TIMEOUT_PROPOSE@ \\
--e config_timeout_prevote=@FIXTURE_CONFIG_TIMEOUT_PREVOTE@ \\
--e config_timeout_precommit=@FIXTURE_CONFIG_TIMEOUT_PRECOMMIT@ \\
--e config_timeout_commit=@FIXTURE_CONFIG_TIMEOUT_COMMIT@ \\
--e client_keyring_backend=@FIXTURE_CLIENT_KEYRING_BACKEND@"
+		initialize $_ri $_ci &
+		_pending_pids="$_pending_pids $!"
 	done
+	wait_pids $_pending_pids
 
 	# generate gentxs
+	_pending_pids=
 	for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
 	do
-		_admin=$(service_name administrator $_ri $_ci)
-
-		service_exec $_admin "cd && ansible-playbook -i inventory genesis.yml \\
--e phase=generate \\
--e daemon_name=@DAEMON_NAME@ \\
--e daemon_home=@DAEMON_HOME@ \\
--e region_index=$_ri \\
--e chain_index=$_ci \\
--e state_bond_denom=@FIXTURE_STATE_BOND_DENOM@ \\
--e state_balance=@FIXTURE_STATE_BALANCE@ \\
--e state_delegation=@FIXTURE_STATE_DELEGATION@"
-		service_fetch $_admin /root/artifact/seat/address.txt $_genesis_dir/address-$_ri.txt
-		service_fetch $_admin /root/artifact/seat/gentx.json $_genesis_dir/gentx-$_ri.json
+		generate_gentxs $_ri $_ci &
+		_pending_pids="$_pending_pids $!"
 	done
+	wait_pids $_pending_pids
 
-	# collect gentx
+	# collect gentxs
 	for _ri in 0
 	do
 		_admin=$(service_name administrator $_ri $_ci)
@@ -101,73 +157,57 @@ do
 	done
 
 	# distribute genesis
+	_pending_pids=
 	for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
 	do
-		_admin=$(service_name administrator $_ri $_ci)
-
-		service_exec $_admin "mkdir -p /root/artifact/genesis"
-		service_push $_admin $_genesis_dir/genesis.json /root/artifact/genesis/
-		service_exec $_admin "cd && ansible-playbook -i inventory genesis.yml \\
--e phase=distribute \\
--e daemon_home=@DAEMON_HOME@"
+		distribute_genesis $_ri $_ci &
+		_pending_pids="$_pending_pids $!"
 	done
+	wait_pids $_pending_pids
 
 	# gather dynamic information
+	_pending_pids=
 	for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
 	do
-		_admin=$(service_name administrator $_ri $_ci)
-
-		service_exec $_admin "cd && ansible-playbook -i inventory config.yml \\
--e phase=gather"
-		mkdir $_dynamic_dir/$_ri
-		service_fetch $_admin /root/artifact/seed/public-ip.txt $_dynamic_dir/$_ri/
-		service_fetch $_admin /root/artifact/seed/node-id.txt $_dynamic_dir/$_ri/
+		gather_configs $_ri $_ci &
+		_pending_pids="$_pending_pids $!"
 	done
+	wait_pids $_pending_pids
 
 	# update dynamic information
+	_pending_pids=
 	for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
 	do
-		_admin=$(service_name administrator $_ri $_ci)
-
-		service_exec $_admin "mkdir -p /root/artifact/seeds"
-		service_push $_admin $_dynamic_dir/. /root/artifact/seeds/
-		service_exec $_admin "cd && ansible-playbook -i inventory config.yml \\
--e phase=apply \\
--e daemon_home=@DAEMON_HOME@ \\
--e region_index=$_ri"
+		apply_configs $_ri $_ci &
+		_pending_pids="$_pending_pids $!"
 	done
+	wait_pids $_pending_pids
 
 	# run cosmovisor
 	for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
 	do
 		_admin=$(service_name administrator $_ri $_ci)
 
-		service_exec $_admin "cd && ansible-playbook -i inventory run.yml"
+		service_exec $_admin "cd && ansible-playbook -i inventory run.yml" &
 	done
 done
 
-# (4 = validator + seed + full + seat)
-num_services=$(expr $NUM_CHAINS '*' $NUM_REGIONS '*' '(' 4 + $NUM_SENTRIES ')')
-
-while true
+unhealthy_services=$(get_services | grep -Ev '^administrator\.')
+while [ -n "$unhealthy_services" ]
 do
-	_num_healthy=0
-	for _service in $(get_services)
+	_services="$unhealthy_services"
+	unhealthy_services=
+	for _service in $_services
 	do
-		if [ $(service_health $_service) = healthy ]
+		if [ $(service_health $_service) != healthy ]
 		then
-			_num_healthy=$(expr $_num_healthy + 1)
-		elif [ $(service_status $_service) != running ]
-		then
-			echo "Error on: " $_service >&2
-			false
+			unhealthy_services="$unhealthy_services $_service"
+			if [ $(service_status $_service) != running ]
+			then
+				echo "Error on: " $_service >&2
+				false
+			fi
+			sleep 1
 		fi
 	done
-
-	if [ $_num_healthy -ge $num_services ]
-	then
-		break
-	fi
-
-	sleep 1
 done
