Use ansible in the tests (#4)
* Use cosmos-sdk 0.47.5

* Use gaia 11.0.0

* Update golang version of the builders

* Use ansible

* Ready for scalables

* Optimize setup-nodes

* Optimize setup-chains

* Use ansible.builtin.service

* Support arbitrary chain ids

* Use local facts

* Refactor

* Add blocksync

* Support multi region again

* Refactor genesis

* Set configs using variables

* Stop using end_host

* Remove unused facts dir preparation

* Detect golang version

* Use github api

* Add sentry scaling test

* Update documentation

* Skip auto for now

* Update documentation

* Move tests to test folder

* Update documentation

* Update workflows

* Guess build image tag

* Do verbose test in workflows

* Provide upgrade name

* Allow changing timeout on the tests

* Set test timeout to 30m in workflows

* Reduce instances of rolling update tests

* Change workflow schedules

* Apply the change of variable name to workflows

* Use gaia 12.0.0

* Use latest versions in in-place migration tests

* Use the first and latest versions in rolling update tests

* Set default test timeout to 10m

* Lower the default number of sentries

diff --git a/fixture/chain/setup-chains.sh.in b/fixture/chain/setup-chains.sh.in
--- a/fixture/chain/setup-chains.sh.in
+++ b/fixture/chain/setup-chains.sh.in
@@ -2,45 +2,173 @@
 
 set -xe
 
-# every variable must not be empty
-assert_variables() {
-	for name in $@
-	do
-		if [ -z "$(eval echo '$'$name)" ]
-		then
-			echo no variable: $name
-			false
-		fi
-	done
+. @CMAKE_SOURCE_DIR@/fixture/util/common.sh
+. @CMAKE_SOURCE_DIR@/fixture/util/service.sh
+
+# TODO: add the fixture
+cosmovisor=@COSMOVISOR_BINARY_DIR@/cosmovisor
+prepare_cosmovisor() {
+	if [ ! -f $cosmovisor ]
+	then
+		cmake --build @CMAKE_BINARY_DIR@ --target build_cosmovisor
+	fi
+}
+
+install_daemon() {
+	local region_id=$1
+	local chain_id=$2
+
+	local admin=$(service_name administrator $region_id $chain_id)
+
+	# push binaries to admin
+	local version=@FIXTURE_DAEMON_VERSION@
+	service_exec $admin "mkdir -p ~/daemon/$version"
+	service_push $admin $cosmovisor /root/
+	# service_push $admin @DAEMON_BINARY_DIR@/$version/bundle.tar.gz ~/daemon/$version/
+	service_push $admin @DAEMON_BINARY_DIR@/$version/bundle.tar.gz /root/
+
+	# install cosmovisor
+	service_exec $admin "cd && ansible-playbook -i inventory cosmovisor.yml \\
+-e src=cosmovisor \\
+-e daemon_name=@DAEMON_NAME@ \\
+-e daemon_home=@DAEMON_HOME@"
+
+	# install daemon
+	service_exec $admin "cd && ansible-playbook -i inventory daemon.yml \\
+-e src=bundle.tar.gz \\
+-e region_id=$region_id \\
+-e chain_id=$chain_id \\
+-e timeout_propose=@FIXTURE_CONFIG_TIMEOUT_PROPOSE@ \\
+-e timeout_prevote=@FIXTURE_CONFIG_TIMEOUT_PREVOTE@ \\
+-e timeout_precommit=@FIXTURE_CONFIG_TIMEOUT_PRECOMMIT@ \\
+-e timeout_commit=@FIXTURE_CONFIG_TIMEOUT_COMMIT@ \\
+-e keyring_backend=@FIXTURE_CLIENT_KEYRING_BACKEND@"
+}
+
+gentx() {
+	local region_id=$1
+	local chain_id=$2
+	local output_dir=$3
+
+	local admin=$(service_name administrator $region_id $chain_id)
+	service_exec $admin "cd && ansible-playbook -i inventory gentx.yml \\
+-e dest=gentx.json \\
+-e bond_denom=@FIXTURE_STATE_BOND_DENOM@ \\
+-e delegation=@FIXTURE_STATE_DELEGATION@"
+	service_fetch $admin /root/gentx.json $output_dir/gentx-$region_id.json
 }
 
 assert_variables NUM_CHAINS \
 				 NUM_REGIONS \
-				 NUM_SENTRIES \
-				 PROJECT_NAME
+				 NUM_SENTRIES
 
-script_dir=$(dirname $(realpath $0))
-# $script_dir/generate-compose.py --name $PROJECT_NAME --chains $NUM_CHAINS --regions $NUM_REGIONS --sentries $NUM_SENTRIES -o $PROJECT_NAME.yml
-$script_dir/generate-compose.py --chains $NUM_CHAINS --regions $NUM_REGIONS --sentries $NUM_SENTRIES -o $PROJECT_NAME.yml
+chain_id=${1:-$(chain_name 0)}
 
-docker-compose -p $PROJECT_NAME -f $PROJECT_NAME.yml up --detach --remove-orphans
+prepare_cosmovisor
 
-# (4 = validator + seed + full + seat)
-num_services=$(expr $NUM_CHAINS '*' $NUM_REGIONS '*' '(' 4 + $NUM_SENTRIES ')')
-
-while true
+pending_pids=
+for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
 do
-	if [ $(docker-compose -p $PROJECT_NAME -f $PROJECT_NAME.yml ps | grep -E '\(healthy\)' | wc -l) -ge $num_services ] 2>/dev/null
-	then
-		break
-	fi
+	_region_id=$(region_name $_ri)
 
-	if [ $(docker-compose -p $PROJECT_NAME -f $PROJECT_NAME.yml ps | grep -E 'Exit' | wc -l) -gt 0 ] 2>/dev/null
-	then
-		echo "Errors in:"
-		docker-compose -p $PROJECT_NAME -f $PROJECT_NAME.yml ps | grep -E 'Exit' | awk '{print $1}'
-		false
-	fi
+	install_daemon $_region_id $chain_id &
+	pending_pids="$pending_pids $!"
+done
+wait_pids $pending_pids
 
-	sleep 1
+gentx_dir=artifact/$chain_id/gentx
+rm -rf $gentx_dir
+mkdir -p $gentx_dir
+pending_pids=
+for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
+do
+	_region_id=$(region_name $_ri)
+
+	gentx $_region_id $chain_id $gentx_dir &
+	pending_pids="$pending_pids $!"
+done
+wait_pids $pending_pids
+
+seed_dir=artifact/$chain_id/seed
+rm -rf $seed_dir
+mkdir -p $seed_dir
+genesis_dir=artifact/$chain_id/genesis
+rm -rf $genesis_dir
+mkdir -p $genesis_dir
+for _ri in 0
+do
+	_region_id=$(region_name $_ri)
+
+	_admin=$(service_name administrator $_region_id $chain_id)
+
+	# configure peers
+	service_exec $_admin "cd && ansible-playbook -i inventory peers.yml \\
+-e dest=seed.json"
+	service_fetch $_admin /root/seed.json $seed_dir/seed-$_region_id.json
+
+	# generate genesis
+	service_exec $_admin "cd && rm -rf gentx"
+	service_push $_admin $gentx_dir /root/gentx
+	service_exec $_admin "cd && ansible-playbook -i inventory genesis.yml \\
+-e dest=genesis.json \\
+-e gentx=gentx \\
+-e bond_denom=@FIXTURE_STATE_BOND_DENOM@ \\
+-e balance=@FIXTURE_STATE_BALANCE@ \\
+-e unbonding_time=@FIXTURE_STATE_UNBONDING_TIME@ \\
+-e min_deposit=@FIXTURE_STATE_MIN_DEPOSIT@ \\
+-e voting_period=@FIXTURE_STATE_VOTING_PERIOD@"
+	service_fetch $_admin /root/genesis.json $genesis_dir/genesis.json
+done
+
+# collect seeds
+cat $seed_dir/seed-$(region_name 0).json | jq -ns '.seeds |= inputs' >$seed_dir/seeds.json
+
+pending_pids=
+for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
+do
+	_region_id=$(region_name $_ri)
+
+	_admin=$(service_name administrator $_region_id $chain_id)
+
+	# configure
+	service_push $_admin $seed_dir/seeds.json /root/seeds.json
+	service_exec $_admin "cd && ansible-playbook -i inventory peers.yml \\
+-e @seeds.json" &
+	pending_pids="$pending_pids $!"
+done
+wait_pids $pending_pids
+
+pending_pids=
+for _ri in $(seq 0 $(expr $NUM_REGIONS - 1))
+do
+	_region_id=$(region_name $_ri)
+
+	_admin=$(service_name administrator $_region_id $chain_id)
+
+	# blocksync
+	service_push $_admin $genesis_dir/genesis.json /root/genesis.json
+	service_exec $_admin "cd && ansible-playbook -i inventory blocksync.yml \\
+-e src=genesis.json" &
+	pending_pids="$pending_pids $!"
+done
+wait_pids $pending_pids
+
+unhealthy_services=$(get_services _ _ $chain_id | grep -Ev '^administrator\.')
+while [ -n "$unhealthy_services" ]
+do
+	_services="$unhealthy_services"
+	unhealthy_services=
+	for _service in $_services
+	do
+		if [ $(service_health $_service) != healthy ]
+		then
+			unhealthy_services="$unhealthy_services $_service"
+			if [ $(service_status $_service) != running ]
+			then
+				echo "Error on: " $_service >&2
+				false
+			fi
+			sleep 1
+		fi
+	done
 done
